repos:
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake --remove-unused-variables --remove-all-unused-imports --ignore-init-module-imports --in-place -r .
        language: python
        types: [ python ]
        pass_filenames: false

      - id: isort
        name: isort
        entry: isort .
        language: python
        types: [ python ]
        pass_filenames: false

      - id: black
        name: black
        entry: black .
        language: python
        types: [python]
        pass_filenames: false
