"""empty message

Revision ID: b23772ae576d
Revises: 1eed22b789b3
Create Date: 2025-09-04 07:20:07.279631

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b23772ae576d"
down_revision: Union[str, Sequence[str], None] = "1eed22b789b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("offers", sa.Column("creator_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "offers", "users", ["creator_id"], ["id"])
    op.sync_enum_values(
        "public", "offertype", ["NEWS", "UNDEFINED", "VACANCIES"], ["NEWS", "VACANCIES"], [("offers", "type")], False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public", "offertype", ["NEWS", "VACANCIES"], ["NEWS", "UNDEFINED", "VACANCIES"], [("offers", "type")], True
    )
    op.drop_constraint(None, "offers", type_="foreignkey")
    op.drop_column("offers", "creator_id")
    # ### end Alembic commands ###
