"""empty message

Revision ID: 1eed22b789b3
Revises: c8adfffe3dd5
Create Date: 2025-09-03 18:34:12.861867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eed22b789b3'
down_revision: Union[str, Sequence[str], None] = 'c8adfffe3dd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('offers', 'type',
                    existing_type=postgresql.ENUM('UNDEFINED', 'NEWS', 'VACANCIES', name='offertype'),
                    nullable=True)
    op.sync_enum_values('public', 'offertype', ['NEWS', 'UNDEFINED', 'VACANCIES'], ['NEWS', 'VACANCIES'],
                        [('offers', 'type')], False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values('public', 'offertype', ['NEWS', 'VACANCIES'], ['NEWS', 'UNDEFINED', 'VACANCIES'],
                        [('offers', 'type')], True)
    op.alter_column('offers', 'type',
                    existing_type=postgresql.ENUM('UNDEFINED', 'NEWS', 'VACANCIES', name='offertype'),
                    nullable=False)
    # ### end Alembic commands ###
